### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by namazso** [tringi/win32-dpi#1]
Have you considered adding a license?
It would be great to be able to use parts of code from this too, not just using it as a resource for figuring out dpi scaling.

**Comment by tringi** [comment]
Alright. I didn't realize it was necessary. Added LICENSE file just now. ISC License should suffice?

**Comment by namazso** [comment]
I prefer using public domain -like licenses (like WTFPL) for example code, but for me this is fine too.

thanks
